

export const ADD_ADMIN = 'ADD_ADMIN';
export const GET_ADMIN = 'GET_ADMIN';

export const SET_CURRENT_USER_TYPE = 'SET_CURRENT_USER_TYPE';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGOUT_ADMIN='LOGOUT_ADMIN';

export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT_USER='LOGOUT_USER';

export const ADD_COURSE = 'ADD_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const ADD_COURSE_IMAGE = 'ADD_COURSE_IMAGE';
export const GET_COURSE_BY_ID = 'GET_COURSE_BY_ID';

export const ADD_SECTION = 'ADD_SECTION';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const GET_SECTION_BY_ID = 'GET_SECTION_BY_ID';
export const DELETE_SECTION = 'DELETE_SECTION';
export const ADD_LESSON = 'ADD_LESSON';
export const GET_LESSON_BY_ID = 'GET_LESSON_BY_ID';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';

export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const ADD_QUIZ = 'ADD_QUIZ';
export const GET_QUIZ = 'GET_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const ADD_VIDEO_THUMBNAIL = 'ADD_VIDEO_THUMBNAIL';
export const ADD_PDF = 'ADD_PDF';
export const DELETE_PDF = 'DELETE_PDF';
export const ADD_AUTHOR_DETAILS = 'ADD_AUTHOR_DETAILS';



export const PUBLISH_COURSE = 'PUBLISH_COURSE';
export const UNPUBLISH_COURSE = 'UNPUBLISH_COURSE';
export const UNPUBLISH_SECTION = 'UNPUBLISH_SECTION';
export const PUBLISH_SECTION = 'PUBLISH_SECTION';
export const PUBLISH_LESSON = 'PUBLISH_LESSON';
export const UNPUBLISH_LESSON = 'UNPUBLISH_LESSON';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_ALL_COURSE_USER = 'GET_ALL_COURSE_USER';
export const GET_USER_COURSE = 'GET_USER_COURSE';
export const ADD_PAYMENT = 'ADD_PAYMENT';

export const GET_USER_SECTION = 'GET_USER_SECTION';
export const GET_USER_LESSON = 'GET_USER_LESSON';
export const GET_USER_QUIZ = 'GET_USER_QUIZ';
export const SUBMIT_QUIZ_ANSWER='SUBMIT_QUIZ_ANSWER';
export const GET_RESULT = 'GET_RESULT';

export const ADD_COUPON = 'ADD_COUPON';
export const GET_COUPON = 'GET_COUPON';
export const ADD_COUPON_TO_COURSE = 'ADD_COUPON_TO_COURSE';
export const UPDATE_COUPON='UPDATE_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';

export const ADD_UPSELL = 'ADD_UPSELL';
export const DELETE_UPSELL = 'DELETE_UPSELL';
export const ADD_USER_ACCOUNT = 'ADD_USER_ACCOUNT';
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export const UPDATE_USER_ACCOUNT = 'UPDATE_USER_ACCOUNT';

export const ADD_RATIO = 'ADD_RATIO';
export const GET_RATIO = 'GET_RATIO';
export const DELETE_RATIO = 'DELETE_RATIO';
export const UPDATE_RATIO='UPDATE_RATIO';


export const GET_USER_COUPON = 'GET_USER_COUPON';
export const UPDATE_USER_COUPON = 'UPDATE_USER_COUPON';

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const GET_TEMPLATE = 'GET_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';

export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const GET_ASSIGNMENT = 'GET_ASSIGNMENT';
export const DELETE_ASSIGNMENT='DELETE_ASSIGNMENT';

export const GET_USER_ASSIGNMENT = 'GET_USER_ASSIGNMENT';
export const ADD_USER_ASSIGNMENT = 'ADD_USER_ASSIGNMENT';

export const ADD_FORM = 'ADD_FORM';
export const GET_FORM = 'GET_FORM';

export const ADD_SEND_OTP = 'ADD_SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const GENERATE_PASSWORD = 'GENERATE_PASSWORD';

export const ADD_SCHEDULE_CALL = 'ADD_SCHEDULE_CALL';
export const GET_MY_BOOKING = 'GET_MY_BOOKING';
export const GET_SCHEDULE_BOOKING = 'GET_SCHEDULE_BOOKING';

export const GET_USER_SCHEDULE_CALL='GET_USER_SCHEDULE_CALL';
export const ADD_USER_SCHEDULE_CALL='ADD_USER_SCHEDULE_CALL';

export const ADD_USER_AFFILIATE_LINK='ADD_USER_AFFILIATE_LINK';
export const GET_AFFILIATE_USER_ID='GET_AFFILIATE_USER_ID';

export const GET_LINK_REQUEST='GET_LINK_REQUEST';
export const UPDATE_ACCEPT_REQUEST='UPDATE_ACCEPT_REQUEST';
export const UPDATE_BLOCK_REQUEST='UPDATE_BLOCK_REQUEST';
export const UPDATE_UNBLOCK_REQUEST='UPDATE_UNBLOCK_REQUEST';
// export const GET_VIDEO_PROCESSING='GET_VIDEO_PROCESSING';

export const ADD_PPT_FILES='ADD_PPT_FILES';

export const GET_ADMIN_USER='GET_ADMIN_USER';
export const ADD_SALE_LINK='ADD_SALE_LINK';

export const ADD_EMBED_VIDEO='ADD_EMBED_VIDEO';
export const ADD_ADMIN_SALE_LINK='ADD_ADMIN_SALE_LINK';

export const GET_COURSE_BY_TITLE='GET_COURSE_BY_TITLE';

export const ALLOW_AFFILIATE_COURSE="ALLOW_AFFILIATE_COURSE";
export const DISALLOW_AFFILIATE_COURSE="DISALLOW_AFFILIATE_COURSE";

export const GET_PUBLIC_COURSE='GET_PUBLIC_COURSE';

export const ADD_TEXT='ADD_TEXT';
export const DELETE_TEXT='DELETE_TEXT';
export const UPDATE_TEXT='UPDATE_TEXT';

export const ADD_NEW_USER='ADD_NEW_USER';
export const GET_ADMIN_BLOCK_USER='GET_ADMIN_BLOCK_USER';

export const UPDATE_BLOCK_USER='UPDATE_BLOCK_USER';
export const UPDATE_UNBLOCK_USER='UPDATE_UNBLOCK_USER';

export const ADD_BULK_USER_TO_COURSE='ADD_BULK_USER_TO_COURSE';



